#include "Tests/displayIntermediateValues.h"
#include "Tests/genKAT.h"
#include "Tests/testDuplex.h"
#include "Tests/testPermutationAndStateMgt.h"
#include "Tests/testSponge.h"
#include "Tests/timing.h"
